version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'jpa'
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: hkjin
      MYSQL_PASSWORD : jin37456
    ports:
      - 3306:3306
    volumes:
        - data:/var/lib/mysql
    # TimeZone: Asia/Seoul
    # command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  redis:
    container_name: redis
    image: redis
    restart: always
    hostname: redis_service
    ports:
      - 6379:6379